### ISSUE TITLE
Support returning a hash-key

### ISSUE THREAD

**Issue by natew** [FormidableLabs/react-fast-compare#31]
This would help for the pattern of `getDerivedStateFromProps` not having to duplicate the children object:

```ts
import { key } from 'react-fast-compare'

  static getDerivedStateFromProps(props, state) {
    if (key(props.children) !== state.childKey) {
      return { childKey: key(props.children) }
    }
    return null
  }
```

**Comment by chrisbolin** [comment]
@natew that is really interesting. I like the thought about performance. As I understand it, though, it'd be a completely different feature, not re-using any of the logic we currently employ, right? 

I ask partially for the same reasons as https://github.com/FormidableLabs/react-fast-compare/issues/29#issuecomment-413091131. I'm just trying to keep this project focused (which is why I am so glad you found https://github.com/FormidableLabs/react-fast-compare/issues/30 !). The other is that I think being really small is a value for us: it even got us [in formik](https://github.com/FormidableLabs/react-fast-compare/issues/13).

**Comment by natew** [comment]
@chrisbolin definitely, probably should be react-fast-hash which is in spirit similar. I need to profile but I think it would dramatically lower memory usage for our current view library, which is storing quite a lot of duplicate props into state right now when it could be storing a hash. So, I may use this library as inspiration for that.
