### ISSUE TITLE
Getters are not considered

### ISSUE THREAD

**Issue by tonio-ramirez** [FormidableLabs/react-fast-compare#65]
```javascript
import isEqual from "react-fast-compare";

class MyClass {

    #a;

    constructor(a) {
        this.#a = a;
     }

    get a() {
        return this.#a;
    }
}

console.log(isEqual(new MyClass(1), new MyClass(2)); // prints "true"
```

**Comment by kitten** [comment]
There's no way to get to these two properties, because `#a` is completely private and hidden, and getters are defined as non-enumerable, e.g.

```js
Object.keys(new MyClass(1)) // [] empty

const x = new MyClass(1)
for (const key in x) { /* no enumerable keys */ }

for (const key in x.constructor.prototype) {
  /* no enumerable prototype keys even */
}
```

That means there's virtually no enumerable property, e.g. differentiating factor on your class.

In stringification functions I'd personally consider two classes that aren't objects (`x.constructor && x.constructor !== Object && keys.length === 0`) to always be unique and compare them by reference equality.
However, in a deep comparison function that's a bad assumption.

There's a solution though :) You can for instance forgo the use of private class properties and make `#a` visible, e.g. by naming it `_a`.

You could also provide a serialisation function, which is actually quite common:

```js
class MyClass {
  // ...
  valueOf() {
    return this.#a;
  }
}
```

Or alternatively you can use `toString` maybe:

```js
class MyClass {
  // ...
  toString() {
    return `[MyClass ${this.#a}]`;
  }
}
```

Currently, `react-fast-compare` due to being specialised doesn't support `toJSON` though.

**Comment by tonio-ramirez** [comment]
I see.  I'll look into using serialization functions or `toString`, then.  Thanks!
